package com.example.remindme.utils

import android.content.Context
import androidx.work.*

/*
 * code by https://dev.to/blazebrain/building-a-reminder-app-with-local-notifications-using-workmanager-api-385f
 * insertion for id by Ula Rauch
 */
class ReminderWorker(val context: Context, val params: WorkerParameters) : Worker(context, params) {

    override fun doWork(): Result {
        NotificationHelper(context = context).createNotification(
            //adaption to use autogenerated reminder id as notification id
            id = inputData.getLong("id", 1).toInt(),
            title = inputData.getString("title").toString(),
            message = inputData.getString("message").toString())

        return Result.success()
    }
}