package com.example.remindme.DB

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.room.*
import com.example.remindme.models.Reminder
import kotlinx.coroutines.flow.Flow

@Dao
interface RememberDao {

    @Insert
    fun addReminder(reminder: Reminder): Long //returns autogenerated ID for inserted reminder (rowID according to some sources, but seems to be equal to the id of the reminder)

    @Delete
    fun deleteReminder(reminder: Reminder)

    @Update
    fun updateReminder(reminder: Reminder)

    @Query("SELECT * from reminders")
    fun getReminders(): Flow<List<Reminder>> //Flow: stream of data, can be read continuously

    @Query("SELECT * from reminders where id=:id")
    fun getReminderByID(id: Long): LiveData<Reminder>

    @Query("DELETE FROM reminders")
    fun deleteAll()

    //TODO: add functions for editReminder etc.
    /*
    @Update
    fun editReminder(reminder: Reminder)
     */
}